name: Development build test

on:
 push:
   branches: [version-3-dev]

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
        name: Checkout source code
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with :
           version: 16.13.0
       
      - name: Build the site
        run: |
          npm install
          npm run build
 
